apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/component: platform

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: config
    files:
      - config/prometheus-jmx.yaml
